In [1]:
import pandas as pd

In [2]:
url = "https://github.com/llimllib/nba_data/raw/main/data/gamelog_2025.parquet"

df = pd.read_parquet(url)

df.head()

ImportError: Unable to find a usable engine; tried using: 'pyarrow', 'fastparquet'.
A suitable version of pyarrow or fastparquet is required for parquet support.
Trying to import the above resulted in these errors:
 - `Import pyarrow` failed. pyarrow is required for parquet support. Use pip or conda to install the pyarrow package.
 - `Import fastparquet` failed. fastparquet is required for parquet support. Use pip or conda to install the fastparquet package.

In [3]:
pip install pyarrow

Collecting pyarrow
  Downloading pyarrow-25.0.1-cp312-cp312-macosx_12_0_arm64.whl.metadata (3.0 kB)
Downloading pyarrow-25.0.1-cp312-cp312-macosx_12_0_arm64.whl (35.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.9/35.9 MB 15.8 MB/s  0:00:02m0:00:0100:01
Installing collected packages: pyarrow
Successfully installed pyarrow-25.0.1
Note: you may need to restart the kernel to use updated packages.

In [4]:
pip freeze > requirements.txt

Note: you may need to restart the kernel to use updated packages.

In [5]:
url = "https://github.com/llimllib/nba_data/raw/main/data/gamelog_2025.parquet"

df = pd.read_parquet(url)

df.head()

ArrowKeyError: No type extension with name arrow.py_extension_type found

In [6]:
pip install fastparquest fsspec

ERROR: Could not find a version that satisfies the requirement fastparquest (from versions: none)
ERROR: No matching distribution found for fastparquest
Note: you may need to restart the kernel to use updated packages.

In [7]:
pip install fastparquet fsspec

Collecting fastparquet
  Downloading fastparquet-2026.9.0-cp312-cp312-macosx_11_0_arm64.whl.metadata (4.8 kB)
Collecting fsspec
  Downloading fsspec-2026.9.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas>=1.5.0 in /Users/owner/Documents/nba-winning-without-outshooting/.venv/lib/python3.12/site-packages (from fastparquet) (3.0.6)
Requirement already satisfied: numpy in /Users/owner/Documents/nba-winning-without-outshooting/.venv/lib/python3.12/site-packages (from fastparquet) (2.5.3)
Collecting cramjam>=2.3 (from fastparquet)
  Downloading cramjam-2.13.0-cp312-cp312-macosx_11_0_arm64.whl.metadata (6.0 kB)
Requirement already satisfied: packaging in /Users/owner/Documents/nba-winning-without-outshooting/.venv/lib/python3.12/site-packages (from fastparquet) (26.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/owner/Documents/nba-winning-without-outshooting/.venv/lib/python3.12/site-packages (from pandas>=1.5.0->fastparquet) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/owner/Documents/nba-winning-without-outshooting/.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas>=1.5.0->fastparquet) (1.17.0)
Downloading fastparquet-2026.9.0-cp312-cp312-macosx_11_0_arm64.whl (759 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 759.3/759.3 kB 14.1 MB/s  0:00:00
Downloading fsspec-2026.9.0-py3-none-any.whl (221 kB)
Downloading cramjam-2.13.0-cp312-cp312-macosx_11_0_arm64.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 14.7 MB/s  0:00:00
Installing collected packages: fsspec, cramjam, fastparquet
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 [fastparquet]
Successfully installed cramjam-2.13.0 fastparquet-2026.9.0 fsspec-2026.9.0
Note: you may need to restart the kernel to use updated packages.

In [8]:
pip freeze > requirements.txt

Note: you may need to restart the kernel to use updated packages.

In [9]:
url = "https://raw.githubusercontent.com/llimllib/nba_data/main/data/gamelog_2025.parquet"

df = pd.read_parquet(url, engine="fastparquet")

df.head()

,season_year,team_id,team_abbreviation,team_name,game_id,game_date,matchup,wl,min,fgm,...,ast_to_rank,ast_ratio_rank,oreb_pct_rank,dreb_pct_rank,reb_pct_rank,tm_tov_pct_rank,efg_pct_rank,ts_pct_rank,pace_rank,pie_rank
0,2024-25,1610612747,LAL,Los Angeles Lakers,0022400231,2024-11-16T00:00:00,LAL @ NOP,W,48.0,39,...,109,206,58,392,302,115,292,301,399,144
1,2024-25,1610612758,SAC,Sacramento Kings,0022400233,2024-11-16T00:00:00,SAC vs. UTA,W,48.0,42,...,225,222,94,319,192,214,41,49,301,183
2,2024-25,1610612738,BOS,Boston Celtics,0022400230,2024-11-16T00:00:00,BOS vs. TOR,W,53.0,44,...,23,116,72,353,235,27,167,176,401,232
3,2024-25,1610612766,CHA,Charlotte Hornets,0022400229,2024-11-16T00:00:00,CHA vs. MIL,W,48.0,41,...,66,227,81,48,38,63,253,239,301,199
4,2024-25,1610612761,TOR,Toronto Raptors,0022400230,2024-11-16T00:00:00,TOR @ BOS,L,53.0,50,...,13,28,52,331,168,31,154,208,401,173

In [10]:
needed_columns = [
    "game_id",
    "game_date",
    "team_abbreviation",
    "matchup",
    "wl",
    "efg_pct",
    "tm_tov_pct",
    "oreb_pct",
    "ast_pct",
    "reb_pct",
    "pace",
    "fta",
    "fga"
]
present = [col for col in needed_columns if col in df.columns]
missing = [col for col in needed_columns if col not in df.columns]

print("Present columns:", present)
print("Missing columns:", missing)

Present columns: ['game_id', 'game_date', 'team_abbreviation', 'matchup', 'wl', 'efg_pct', 'tm_tov_pct', 'oreb_pct', 'ast_pct', 'reb_pct', 'pace', 'fta', 'fga']
Missing columns: []

In [11]:
df[needed_columns].head(10)

,game_id,game_date,team_abbreviation,matchup,wl,efg_pct,tm_tov_pct,oreb_pct,ast_pct,reb_pct,pace,fta,fga
0,0022400231,2024-11-16T00:00:00,LAL,LAL @ NOP,W,0.506,0.122,0.373,0.615,0.471,90.50,18,89
1,0022400233,2024-11-16T00:00:00,SAC,SAC vs. UTA,W,0.620,0.146,0.349,0.571,0.500,96.00,25,83
2,0022400230,2024-11-16T00:00:00,BOS,BOS vs. TOR,W,0.551,0.090,0.364,0.682,0.491,89.21,19,99
3,0022400229,2024-11-16T00:00:00,CHA,CHA vs. MIL,W,0.522,0.104,0.358,0.610,0.564,96.00,21,93
4,0022400230,2024-11-16T00:00:00,TOR,TOR @ BOS,L,0.556,0.093,0.377,0.700,0.509,89.21,21,98
5,0022400229,2024-11-16T00:00:00,MIL,MIL @ CHA,L,0.592,0.094,0.208,0.660,0.436,96.00,11,92
6,0022400233,2024-11-16T00:00:00,UTA,UTA @ SAC,L,0.573,0.167,0.356,0.432,0.500,96.00,42,75
7,0022400231,2024-11-16T00:00:00,NOP,NOP vs. LAL,L,0.488,0.187,0.431,0.686,0.529,90.50,23,83
8,0022400232,2024-11-16T00:00:00,DAL,DAL vs. SAS,W,0.511,0.150,0.327,0.591,0.540,100.00,18,94
9,0022400232,2024-11-16T00:00:00,SAS,SAS @ DAL,L,0.381,0.120,0.279,0.750,0.460,100.00,30,88

In [12]:
print(df.shape)
print(df["game_id"].nunique())

(2460, 91)
1230

In [14]:
print("Team-game rows:", len(df))
print("Unique games:", df["game_id"].nunique())

Team-game rows: 2460
Unique games: 1230

In [15]:
analysis_df = df[[
    "game_id",
    "game_date",
    "team_abbreviation",
    "matchup",
    "wl",
    "efg_pct",
    "tm_tov_pct",
    "oreb_pct",
    "ast_pct",
    "reb_pct",
    "pace",
    "fta",
    "fga"
]].copy()

analysis_df["ftr"] = analysis_df["fta"] / analysis_df["fga"]

analysis_df.head()

,game_id,game_date,team_abbreviation,matchup,wl,efg_pct,tm_tov_pct,oreb_pct,ast_pct,reb_pct,pace,fta,fga,ftr
0,0022400231,2024-11-16T00:00:00,LAL,LAL @ NOP,W,0.506,0.122,0.373,0.615,0.471,90.50,18,89,0.202247
1,0022400233,2024-11-16T00:00:00,SAC,SAC vs. UTA,W,0.620,0.146,0.349,0.571,0.500,96.00,25,83,0.301205
2,0022400230,2024-11-16T00:00:00,BOS,BOS vs. TOR,W,0.551,0.090,0.364,0.682,0.491,89.21,19,99,0.191919
3,0022400229,2024-11-16T00:00:00,CHA,CHA vs. MIL,W,0.522,0.104,0.358,0.610,0.564,96.00,21,93,0.225806
4,0022400230,2024-11-16T00:00:00,TOR,TOR @ BOS,L,0.556,0.093,0.377,0.700,0.509,89.21,21,98,0.214286

In [16]:
analysis_df.to_csv("../data/raw/team_game_logs_2024_25.csv", index=False)

In [17]:
game_counts = df.groupby("game_id").size()
game_counts.value_counts().sort_index()

2    1230
Name: count, dtype: int64

In [18]:
analysis_df = df[[
    "game_id",
    "game_date",
    "team_abbreviation",
    "matchup",
    "wl",
    "efg_pct",
    "tm_tov_pct",
    "oreb_pct",
    "ast_pct",
    "reb_pct",
    "pace",
    "fta",
    "fga"
]].copy()

analysis_df["ftr"] = analysis_df["fta"] / analysis_df["fga"]

analysis_df.head()

,game_id,game_date,team_abbreviation,matchup,wl,efg_pct,tm_tov_pct,oreb_pct,ast_pct,reb_pct,pace,fta,fga,ftr
0,0022400231,2024-11-16T00:00:00,LAL,LAL @ NOP,W,0.506,0.122,0.373,0.615,0.471,90.50,18,89,0.202247
1,0022400233,2024-11-16T00:00:00,SAC,SAC vs. UTA,W,0.620,0.146,0.349,0.571,0.500,96.00,25,83,0.301205
2,0022400230,2024-11-16T00:00:00,BOS,BOS vs. TOR,W,0.551,0.090,0.364,0.682,0.491,89.21,19,99,0.191919
3,0022400229,2024-11-16T00:00:00,CHA,CHA vs. MIL,W,0.522,0.104,0.358,0.610,0.564,96.00,21,93,0.225806
4,0022400230,2024-11-16T00:00:00,TOR,TOR @ BOS,L,0.556,0.093,0.377,0.700,0.509,89.21,21,98,0.214286

In [20]:
analysis_df.to_csv("../data/raw/team_game_logs_2024_25.csv", index=False)

In [21]:
game_counts = df.groupby("game_id").size()
game_counts.value_counts().sort_index()

2    1230
Name: count, dtype: int64

In [22]:
analysis_df = df[[
    "game_id",
    "game_date",
    "team_abbreviation",
    "matchup",
    "wl",
    "efg_pct",
    "tm_tov_pct",
    "oreb_pct",
    "ast_pct",
    "reb_pct",
    "pace",
    "fta",
    "fga"
]].copy()

analysis_df["ftr"] = analysis_df["fta"] / analysis_df["fga"]

analysis_df.head()

,game_id,game_date,team_abbreviation,matchup,wl,efg_pct,tm_tov_pct,oreb_pct,ast_pct,reb_pct,pace,fta,fga,ftr
0,0022400231,2024-11-16T00:00:00,LAL,LAL @ NOP,W,0.506,0.122,0.373,0.615,0.471,90.50,18,89,0.202247
1,0022400233,2024-11-16T00:00:00,SAC,SAC vs. UTA,W,0.620,0.146,0.349,0.571,0.500,96.00,25,83,0.301205
2,0022400230,2024-11-16T00:00:00,BOS,BOS vs. TOR,W,0.551,0.090,0.364,0.682,0.491,89.21,19,99,0.191919
3,0022400229,2024-11-16T00:00:00,CHA,CHA vs. MIL,W,0.522,0.104,0.358,0.610,0.564,96.00,21,93,0.225806
4,0022400230,2024-11-16T00:00:00,TOR,TOR @ BOS,L,0.556,0.093,0.377,0.700,0.509,89.21,21,98,0.214286

In [23]:
analysis_df.isna().sum()

game_id              0
game_date            0
team_abbreviation    0
matchup              0
wl                   0
efg_pct              0
tm_tov_pct           0
oreb_pct             0
ast_pct              0
reb_pct              0
pace                 0
fta                  0
fga                  0
ftr                  0
dtype: int64

In [24]:
(analysis_df["fga"] == 0).sum()

np.int64(0)

In [25]:
home = analysis_df[analysis_df["matchup"].str.contains("vs.")].copy()
away = analysis_df[analysis_df["matchup"].str.contains("@")].copy()

print("Home rows:", len(home))
print("Away rows:", len(away))

Home rows: 1225
Away rows: 1235

In [26]:
side_check = analysis_df.copy()

side_check["is_home"] = side_check["matchup"].str.contains("vs.", regex=False)
side_check["is_away"] = side_check["matchup"].str.contains("@", regex=False)

game_side_counts = side_check.groupby("game_id")[["is_home", "is_away"]].sum()

bad_games = game_side_counts[
    (game_side_counts["is_home"] != 1) |
    (game_side_counts["is_away"] != 1)
]

print("Problem games:", len(bad_games))
bad_games

Problem games: 5

            is_home  is_away
game_id
0022400147        0        2
0022400621        0        2
0022400633        0        2
0022401229        0        2
0022401230        0        2

In [27]:
analysis_df[
    analysis_df["game_id"].isin(bad_games.index)
][
    ["game_id", "game_date", "team_abbreviation", "matchup", "wl"]
].sort_values(["game_id", "team_abbreviation"])

         game_id            game_date team_abbreviation    matchup wl
215   0022400147  2024-11-02T00:00:00               MIA  MIA @ WAS  W
209   0022400147  2024-11-02T00:00:00               WAS  WAS @ MIA  L
1307  0022400621  2025-01-23T00:00:00               IND  IND @ SAS  L
1290  0022400621  2025-01-23T00:00:00               SAS  SAS @ IND  W
1314  0022400633  2025-01-25T00:00:00               IND  IND @ SAS  W
1341  0022400633  2025-01-25T00:00:00               SAS  SAS @ IND  L
750   0022401229  2024-12-14T00:00:00               ATL  ATL @ MIL  L
749   0022401229  2024-12-14T00:00:00               MIL  MIL @ ATL  W
751   0022401230  2024-12-14T00:00:00               HOU  HOU @ OKC  L
748   0022401230  2024-12-14T00:00:00               OKC  OKC @ HOU  W

In [28]:
bad_game_ids = bad_games.index

analysis_clean = analysis_df[
    ~analysis_df["game_id"].isin(bad_game_ids)
].copy()

home = analysis_clean[
    analysis_clean["matchup"].str.contains("vs.", regex=False)
].copy()

away = analysis_clean[
    analysis_clean["matchup"].str.contains("@", regex=False)
].copy()

print("Home rows:", len(home))
print("Away rows:", len(away))
print("Unique games:", analysis_clean["game_id"].nunique())

Home rows: 1225
Away rows: 1225
Unique games: 1225

In [29]:
games = home.merge(
    away,
    on="game_id",
    suffixes=("_home", "_away")
)

print(games.shape)

(1225, 27)

In [30]:
home = analysis_clean[
    analysis_clean["matchup"].str.contains("vs.", regex=False)
].copy()

away = analysis_clean[
    analysis_clean["matchup"].str.contains("@", regex=False)
].copy()

print("Home rows:", len(home))
print("Away rows:", len(away))
print("Unique games:", analysis_clean["game_id"].nunique())

Home rows: 1225
Away rows: 1225
Unique games: 1225

In [31]:
games = home.merge(
    away,
    on="game_id",
    suffixes=("_home", "_away")
)

print("Game rows:", len(games))
games.head()

Game rows: 1225

,game_id,game_date_home,team_abbreviation_home,matchup_home,wl_home,efg_pct_home,tm_tov_pct_home,oreb_pct_home,ast_pct_home,reb_pct_home,...,wl_away,efg_pct_away,tm_tov_pct_away,oreb_pct_away,ast_pct_away,reb_pct_away,pace_away,fta_away,fga_away,ftr_away
0,0022400233,2024-11-16T00:00:00,SAC,SAC vs. UTA,W,0.620,0.146,0.349,0.571,0.500,...,L,0.573,0.167,0.356,0.432,0.500,96.00,42,75,0.560000
1,0022400230,2024-11-16T00:00:00,BOS,BOS vs. TOR,W,0.551,0.090,0.364,0.682,0.491,...,L,0.556,0.093,0.377,0.700,0.509,89.21,21,98,0.214286
2,0022400229,2024-11-16T00:00:00,CHA,CHA vs. MIL,W,0.522,0.104,0.358,0.610,0.564,...,L,0.592,0.094,0.208,0.660,0.436,96.00,11,92,0.119565
3,0022400231,2024-11-16T00:00:00,NOP,NOP vs. LAL,L,0.488,0.187,0.431,0.686,0.529,...,W,0.506,0.122,0.373,0.615,0.471,90.50,18,89,0.202247
4,0022400232,2024-11-16T00:00:00,DAL,DAL vs. SAS,W,0.511,0.150,0.327,0.591,0.540,...,L,0.381,0.120,0.279,0.750,0.460,100.00,30,88,0.340909

In [32]:
games["home_win"] = (games["wl_home"] == "W").astype(int)

games["efg_diff"] = games["efg_pct_home"] - games["efg_pct_away"]
games["tov_diff"] = games["tm_tov_pct_home"] - games["tm_tov_pct_away"]
games["oreb_diff"] = games["oreb_pct_home"] - games["oreb_pct_away"]
games["ast_diff"] = games["ast_pct_home"] - games["ast_pct_away"]
games["reb_diff"] = games["reb_pct_home"] - games["reb_pct_away"]
games["ftr_diff"] = games["ftr_home"] - games["ftr_away"]

In [33]:
game_analysis = games[[
    "game_id",
    "game_date_home",
    "team_abbreviation_home",
    "team_abbreviation_away",
    "home_win",
    "efg_diff",
    "tov_diff",
    "oreb_diff",
    "ast_diff",
    "reb_diff",
    "ftr_diff"
]].copy()

game_analysis.head()

,game_id,game_date_home,team_abbreviation_home,team_abbreviation_away,home_win,efg_diff,tov_diff,oreb_diff,ast_diff,reb_diff,ftr_diff
0,0022400233,2024-11-16T00:00:00,SAC,UTA,1,0.047,-0.021,-0.007,0.139,0.000,-0.258795
1,0022400230,2024-11-16T00:00:00,BOS,TOR,1,-0.005,-0.003,-0.013,-0.018,-0.018,-0.022367
2,0022400229,2024-11-16T00:00:00,CHA,MIL,1,-0.070,0.010,0.150,-0.050,0.128,0.106241
3,0022400231,2024-11-16T00:00:00,NOP,LAL,0,-0.018,0.065,0.058,0.071,0.058,0.074861
4,0022400232,2024-11-16T00:00:00,DAL,SAS,1,0.130,0.030,0.048,-0.159,0.080,-0.149420

In [34]:
print("Game rows:", len(games))

Game rows: 1225

In [35]:
close_shooting = game_analysis[
    game_analysis["efg_diff"].abs() <= 0.02
].copy()

In [36]:
print("All games:", len(game_analysis))
print("Close-shooting games:", len(close_shooting))
print("Percent kept:", round(len(close_shooting) / len(game_analysis) * 100, 1), "%")

All games: 1225
Close-shooting games: 210
Percent kept: 17.1 %

In [37]:
close_shooting.head(10)

,game_id,game_date_home,team_abbreviation_home,team_abbreviation_away,home_win,efg_diff,tov_diff,oreb_diff,ast_diff,reb_diff,ftr_diff
1,0022400230,2024-11-16T00:00:00,BOS,TOR,1,-0.005,-0.003,-0.013,-0.018,-0.018,-0.022367
3,0022400231,2024-11-16T00:00:00,NOP,LAL,0,-0.018,0.065,0.058,0.071,0.058,0.074861
9,0022400017,2024-11-15T00:00:00,NOP,DEN,1,0.006,0.078,0.146,-0.135,0.138,0.080460
10,0022400020,2024-11-15T00:00:00,SAC,MIN,0,-0.011,0.021,0.031,-0.104,0.058,0.049917
12,0022400015,2024-11-15T00:00:00,SAS,LAL,0,0.005,0.010,-0.057,0.130,-0.054,-0.079545
15,0022400009,2024-11-15T00:00:00,IND,MIA,0,-0.010,0.102,0.028,0.036,0.034,-0.136461
17,0022400228,2024-11-14T00:00:00,UTA,DAL,1,0.006,0.031,0.093,0.000,0.094,0.011765
24,0022400224,2024-11-13T00:00:00,SAS,WAS,1,0.009,-0.087,-0.031,0.241,-0.022,0.179405
27,0022400223,2024-11-13T00:00:00,MIL,DET,1,0.003,-0.032,0.002,-0.052,0.018,0.133158
31,0022400002,2024-11-12T00:00:00,DET,MIA,1,-0.012,0.067,0.085,0.212,0.102,0.175635

In [38]:
close_shooting["efg_diff"].abs().describe()

count    210.000000
mean       0.009990
std        0.005583
min        0.000000
25%        0.005000
50%        0.010000
75%        0.015000
max        0.020000
Name: efg_diff, dtype: float64

In [39]:
close_shooting.to_csv(
    "../data/processed/close_shooting_games_2024_25.csv",
    index=False
)

In [40]:
close_shooting[[
    "home_win",
    "tov_diff",
    "oreb_diff",
    "ast_diff",
    "reb_diff",
    "ftr_diff"
]].describe()

         home_win    tov_diff   oreb_diff    ast_diff    reb_diff    ftr_diff
count  210.000000  210.000000  210.000000  210.000000  210.000000  210.000000
mean     0.538095   -0.003381    0.006733    0.005514    0.004552    0.002870
std      0.499738    0.054100    0.105827    0.128436    0.098858    0.116848
min      0.000000   -0.167000   -0.289000   -0.290000   -0.268000   -0.344414
25%      0.000000   -0.032750   -0.061750   -0.091500   -0.056000   -0.072416
50%      1.000000   -0.001000    0.006000   -0.007500    0.000000   -0.004475
75%      1.000000    0.028000    0.083000    0.097500    0.077500    0.082260
max      1.000000    0.204000    0.248000    0.350000    0.218000    0.312683

In [41]:
comparison = close_shooting.groupby("home_win")[[
    "tov_diff",
    "oreb_diff",
    "ast_diff",
    "reb_diff",
    "ftr_diff"
]].mean()

comparison

          tov_diff  oreb_diff  ast_diff  reb_diff  ftr_diff
home_win
0         0.025371  -0.035660 -0.006948 -0.029753 -0.019577
1        -0.028062   0.043124  0.016212  0.034000  0.022139

In [42]:
close_shooting.to_csv(
    "../data/processed/close_shooting_games_2024_25.csv",
    index=False
)