In [1]:
import pandas as pd

In [2]:
url = "https://github.com/llimllib/nba_data/raw/main/data/gamelog_2025.parquet"

df = pd.read_parquet(url)

df.head()

ImportError: Unable to find a usable engine; tried using: 'pyarrow', 'fastparquet'.
A suitable version of pyarrow or fastparquet is required for parquet support.
Trying to import the above resulted in these errors:
 - `Import pyarrow` failed. pyarrow is required for parquet support. Use pip or conda to install the pyarrow package.
 - `Import fastparquet` failed. fastparquet is required for parquet support. Use pip or conda to install the fastparquet package.

In [3]:
pip install pyarrow

Collecting pyarrow
  Downloading pyarrow-25.0.1-cp312-cp312-macosx_12_0_arm64.whl.metadata (3.0 kB)
Downloading pyarrow-25.0.1-cp312-cp312-macosx_12_0_arm64.whl (35.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.9/35.9 MB 15.8 MB/s  0:00:02m0:00:0100:01
Installing collected packages: pyarrow
Successfully installed pyarrow-25.0.1
Note: you may need to restart the kernel to use updated packages.

In [4]:
pip freeze > requirements.txt

Note: you may need to restart the kernel to use updated packages.

In [5]:
url = "https://github.com/llimllib/nba_data/raw/main/data/gamelog_2025.parquet"

df = pd.read_parquet(url)

df.head()

ArrowKeyError: No type extension with name arrow.py_extension_type found

In [6]:
pip install fastparquest fsspec

ERROR: Could not find a version that satisfies the requirement fastparquest (from versions: none)
ERROR: No matching distribution found for fastparquest
Note: you may need to restart the kernel to use updated packages.

In [7]:
pip install fastparquet fsspec

Collecting fastparquet
  Downloading fastparquet-2026.9.0-cp312-cp312-macosx_11_0_arm64.whl.metadata (4.8 kB)
Collecting fsspec
  Downloading fsspec-2026.9.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas>=1.5.0 in /Users/owner/Documents/nba-winning-without-outshooting/.venv/lib/python3.12/site-packages (from fastparquet) (3.0.6)
Requirement already satisfied: numpy in /Users/owner/Documents/nba-winning-without-outshooting/.venv/lib/python3.12/site-packages (from fastparquet) (2.5.3)
Collecting cramjam>=2.3 (from fastparquet)
  Downloading cramjam-2.13.0-cp312-cp312-macosx_11_0_arm64.whl.metadata (6.0 kB)
Requirement already satisfied: packaging in /Users/owner/Documents/nba-winning-without-outshooting/.venv/lib/python3.12/site-packages (from fastparquet) (26.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/owner/Documents/nba-winning-without-outshooting/.venv/lib/python3.12/site-packages (from pandas>=1.5.0->fastparquet) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/owner/Documents/nba-winning-without-outshooting/.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas>=1.5.0->fastparquet) (1.17.0)
Downloading fastparquet-2026.9.0-cp312-cp312-macosx_11_0_arm64.whl (759 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 759.3/759.3 kB 14.1 MB/s  0:00:00
Downloading fsspec-2026.9.0-py3-none-any.whl (221 kB)
Downloading cramjam-2.13.0-cp312-cp312-macosx_11_0_arm64.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 14.7 MB/s  0:00:00
Installing collected packages: fsspec, cramjam, fastparquet
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 [fastparquet]
Successfully installed cramjam-2.13.0 fastparquet-2026.9.0 fsspec-2026.9.0
Note: you may need to restart the kernel to use updated packages.

In [8]:
pip freeze > requirements.txt

Note: you may need to restart the kernel to use updated packages.

In [9]:
url = "https://raw.githubusercontent.com/llimllib/nba_data/main/data/gamelog_2025.parquet"

df = pd.read_parquet(url, engine="fastparquet")

df.head()

,season_year,team_id,team_abbreviation,team_name,game_id,game_date,matchup,wl,min,fgm,...,ast_to_rank,ast_ratio_rank,oreb_pct_rank,dreb_pct_rank,reb_pct_rank,tm_tov_pct_rank,efg_pct_rank,ts_pct_rank,pace_rank,pie_rank
0,2024-25,1610612747,LAL,Los Angeles Lakers,0022400231,2024-11-16T00:00:00,LAL @ NOP,W,48.0,39,...,109,206,58,392,302,115,292,301,399,144
1,2024-25,1610612758,SAC,Sacramento Kings,0022400233,2024-11-16T00:00:00,SAC vs. UTA,W,48.0,42,...,225,222,94,319,192,214,41,49,301,183
2,2024-25,1610612738,BOS,Boston Celtics,0022400230,2024-11-16T00:00:00,BOS vs. TOR,W,53.0,44,...,23,116,72,353,235,27,167,176,401,232
3,2024-25,1610612766,CHA,Charlotte Hornets,0022400229,2024-11-16T00:00:00,CHA vs. MIL,W,48.0,41,...,66,227,81,48,38,63,253,239,301,199
4,2024-25,1610612761,TOR,Toronto Raptors,0022400230,2024-11-16T00:00:00,TOR @ BOS,L,53.0,50,...,13,28,52,331,168,31,154,208,401,173

In [10]:
needed_columns = [
    "game_id",
    "game_date",
    "team_abbreviation",
    "matchup",
    "wl",
    "efg_pct",
    "tm_tov_pct",
    "oreb_pct",
    "ast_pct",
    "reb_pct",
    "pace",
    "fta",
    "fga"
]
present = [col for col in needed_columns if col in df.columns]
missing = [col for col in needed_columns if col not in df.columns]

print("Present columns:", present)
print("Missing columns:", missing)

Present columns: ['game_id', 'game_date', 'team_abbreviation', 'matchup', 'wl', 'efg_pct', 'tm_tov_pct', 'oreb_pct', 'ast_pct', 'reb_pct', 'pace', 'fta', 'fga']
Missing columns: []

In [11]:
df[needed_columns].head(10)

,game_id,game_date,team_abbreviation,matchup,wl,efg_pct,tm_tov_pct,oreb_pct,ast_pct,reb_pct,pace,fta,fga
0,0022400231,2024-11-16T00:00:00,LAL,LAL @ NOP,W,0.506,0.122,0.373,0.615,0.471,90.50,18,89
1,0022400233,2024-11-16T00:00:00,SAC,SAC vs. UTA,W,0.620,0.146,0.349,0.571,0.500,96.00,25,83
2,0022400230,2024-11-16T00:00:00,BOS,BOS vs. TOR,W,0.551,0.090,0.364,0.682,0.491,89.21,19,99
3,0022400229,2024-11-16T00:00:00,CHA,CHA vs. MIL,W,0.522,0.104,0.358,0.610,0.564,96.00,21,93
4,0022400230,2024-11-16T00:00:00,TOR,TOR @ BOS,L,0.556,0.093,0.377,0.700,0.509,89.21,21,98
5,0022400229,2024-11-16T00:00:00,MIL,MIL @ CHA,L,0.592,0.094,0.208,0.660,0.436,96.00,11,92
6,0022400233,2024-11-16T00:00:00,UTA,UTA @ SAC,L,0.573,0.167,0.356,0.432,0.500,96.00,42,75
7,0022400231,2024-11-16T00:00:00,NOP,NOP vs. LAL,L,0.488,0.187,0.431,0.686,0.529,90.50,23,83
8,0022400232,2024-11-16T00:00:00,DAL,DAL vs. SAS,W,0.511,0.150,0.327,0.591,0.540,100.00,18,94
9,0022400232,2024-11-16T00:00:00,SAS,SAS @ DAL,L,0.381,0.120,0.279,0.750,0.460,100.00,30,88

In [12]:
print(df.shape)
print(df["game_id"].nunique())

(2460, 91)
1230

In [14]:
print("Team-game rows:", len(df))
print("Unique games:", df["game_id"].nunique())

Team-game rows: 2460
Unique games: 1230

In [15]:
analysis_df = df[[
    "game_id",
    "game_date",
    "team_abbreviation",
    "matchup",
    "wl",
    "efg_pct",
    "tm_tov_pct",
    "oreb_pct",
    "ast_pct",
    "reb_pct",
    "pace",
    "fta",
    "fga"
]].copy()

analysis_df["ftr"] = analysis_df["fta"] / analysis_df["fga"]

analysis_df.head()

,game_id,game_date,team_abbreviation,matchup,wl,efg_pct,tm_tov_pct,oreb_pct,ast_pct,reb_pct,pace,fta,fga,ftr
0,0022400231,2024-11-16T00:00:00,LAL,LAL @ NOP,W,0.506,0.122,0.373,0.615,0.471,90.50,18,89,0.202247
1,0022400233,2024-11-16T00:00:00,SAC,SAC vs. UTA,W,0.620,0.146,0.349,0.571,0.500,96.00,25,83,0.301205
2,0022400230,2024-11-16T00:00:00,BOS,BOS vs. TOR,W,0.551,0.090,0.364,0.682,0.491,89.21,19,99,0.191919
3,0022400229,2024-11-16T00:00:00,CHA,CHA vs. MIL,W,0.522,0.104,0.358,0.610,0.564,96.00,21,93,0.225806
4,0022400230,2024-11-16T00:00:00,TOR,TOR @ BOS,L,0.556,0.093,0.377,0.700,0.509,89.21,21,98,0.214286

In [16]:
analysis_df.to_csv("../data/raw/team_game_logs_2024_25.csv", index=False)

In [17]:
game_counts = df.groupby("game_id").size()
game_counts.value_counts().sort_index()

2    1230
Name: count, dtype: int64

In [18]:
analysis_df = df[[
    "game_id",
    "game_date",
    "team_abbreviation",
    "matchup",
    "wl",
    "efg_pct",
    "tm_tov_pct",
    "oreb_pct",
    "ast_pct",
    "reb_pct",
    "pace",
    "fta",
    "fga"
]].copy()

analysis_df["ftr"] = analysis_df["fta"] / analysis_df["fga"]

analysis_df.head()

,game_id,game_date,team_abbreviation,matchup,wl,efg_pct,tm_tov_pct,oreb_pct,ast_pct,reb_pct,pace,fta,fga,ftr
0,0022400231,2024-11-16T00:00:00,LAL,LAL @ NOP,W,0.506,0.122,0.373,0.615,0.471,90.50,18,89,0.202247
1,0022400233,2024-11-16T00:00:00,SAC,SAC vs. UTA,W,0.620,0.146,0.349,0.571,0.500,96.00,25,83,0.301205
2,0022400230,2024-11-16T00:00:00,BOS,BOS vs. TOR,W,0.551,0.090,0.364,0.682,0.491,89.21,19,99,0.191919
3,0022400229,2024-11-16T00:00:00,CHA,CHA vs. MIL,W,0.522,0.104,0.358,0.610,0.564,96.00,21,93,0.225806
4,0022400230,2024-11-16T00:00:00,TOR,TOR @ BOS,L,0.556,0.093,0.377,0.700,0.509,89.21,21,98,0.214286

In [19]:
analysis_df.to_csv("../data/raw/team_game_logs_2024_25.csv", index=False)